import h5py

def read_bricks_hdf(fname, return_params=False, return_pids=False):
    '''
    Read halo catalog from the HDF5 file generated by Halomaker.
    
    Parameters
    ----------
    fname : str
        The path to the HDF5 file.
    return_params : bool, optional
        Whether to return the parameters stored in the header and input groups. Default is False.
    return_pids : bool, optional
        Whether to return the particle IDs and indices stored in the member group. Default is False.
    
    Returns
    -------
    halo : numpy structured array
        The halo catalog with positions and radii converted to code unit.
    params : dict, optional
        The parameters stored in the header and input groups. Only returned if return_params is True.
    pids : numpy array, optional
        The particle IDs of the halo members. Only returned if return_pids is True.
    indices : numpy array, optional
        The indices of the halo members. Only returned if return_pids is True.

    Example
    -------
    >>> fname = "tree_bricks00001.h5"
    >>> halo = read_bricks_hdf(fname)
    or
    >>> halo, params = read_bricks_hdf(fname, return_params=True)
    or
    >>> halo, params, pids, indices = read_bricks_hdf(fname, return_params=True, return_pids=True)    
    '''
    with h5py.File(fname, 'r') as f:
        catalog = f['catalog'] # group
        halo = catalog['halo'][:] # dataset
        boxsize2 = f['header'].attrs['boxsize2']
        aexp = f['header'].attrs['aexp']
        unitMpc = 1 / ( aexp * boxsize2 )
        halo['px'] = halo['px'] * unitMpc + 1
        halo['py'] = halo['py'] * unitMpc + 1
        halo['pz'] = halo['pz'] * unitMpc + 1
        halo['r'] = halo['r'] * unitMpc
        halo['rvir'] = halo['rvir'] * unitMpc

        if return_params:
            header = f['header'] # group
            finput = f['input'] # group
            params = dict(header.attrs)
            params.update(finput.attrs)
            if return_pids:
                pids = f['member']['pids'][:] # dataset
                indices = f['member']['index'][:] # dataset
                return halo, params, pids, indices
            return halo, params

        return halo
    
